# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!
target 'Plan a Movie Night' do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Facebook-iOS-SDK'

end

target 'Plan a Movie NightTests' do

end

