# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Plan a Movie Night' do
    
source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking', '~> 1.0'
    

end

target 'Plan a Movie NightTests' do

end

